### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by rootCircle** [rootCircle/codemark-cli#10]
# Motivation
- Currently, because the `secrets.py` is required to be setup manually, so in absence of that when user invoke `codemark --help` then some strange "Module" Error occurs, which is irritating in first place.
- Solving it might help devs start working on feature that don't require those env keys at all in future.

## Possible Implementation
- Setup up your environment with the instructions in [docs/INSTALL.md](docs/INSTALL.md). 
- Then, try moving content of value from hard-coded string  to the values in environment variables.
- Ensure not to rename any variable, as it might break the code.

**Comment by rootCircle** [comment]
One can follow #8, for setting up Firebase environment, before it's merged!

**Comment by Kota-Karthik** [comment]
@rootCircle 
I am interested in doing this issue
So kindly assign me this!!
Thank You : )

**Comment by rootCircle** [comment]
Sure, go ahead!
