### ISSUE TITLE
Migrate setup.py to pyproject.toml

### ISSUE THREAD

**Issue by rootCircle** [rootCircle/codemark-cli#3]
# Motivation
setup.py is deprecated in support for pyproject.toml, so we need to switch in fast before it gets deprecated!

## Resources
- https://stackoverflow.com/questions/72832052/is-there-a-simple-way-to-convert-setup-py-to-pyproject-toml
- https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
- https://setuptools.pypa.io/en/latest/userguide/quickstart.html#development-mode

**Comment by Kota-Karthik** [comment]
hi @rootCircle 
I would be very delighted to do this issue 
So kindly assign me this issue !!
Thank You : )

**Comment by Him7n** [comment]
hi there @rootCircle .. I'd be happy to work on this issue.. :)

**Comment by rootCircle** [comment]
> hi @rootCircle
I would be very delighted to do this issue
So kindly assign me this issue !!
Thank You : )

Sure! Go ahead! Ping me if you need any help!

**Comment by rootCircle** [comment]
There is an exact implementation of the PR, for the feature we might be requiring. Do check in the required docs in changes in this PR https://github.com/pallets/click/pull/2543/files. If you find it helpful!
