### ISSUE TITLE
Add Contibuting.md file

### ISSUE THREAD

**Issue by real-Vansh-Khare** [rootCircle/codemark-cli#6]
### Motivation
The project does not have a contributing.md file which needs to be added

### Guidelines for documentation
- Skim out the documentation instructions from readme.md and put them in contributing.md file.
- Add instructions on how to
    -  install python
    - setup virtual environment
    - install the software
    - run the command live
- Also include instructions on recommended editor and associated extensions.

**Comment by Him7n** [comment]
@real-Vansh-Khare 
if this issue is available I would like to work on it

**Comment by rootCircle** [comment]
Sure go ahead! Tell me if you need any help!
